### PR TITLE
function is so often used, that there should be just one key press needed

### PR DESCRIPTION
**Pull request by capaj**

### CODE REVIEW

**Comment by zenorocha** [comment]
`console.log` is also very used, we could use `c`.  This goes on and on for many commands because some people use a certain snippet more than the other one. I think it's better for us to follow the same two/three letter pattern for every snippet.

Thanks for the PR!

**Comment by capaj** [comment]
@zenorocha well I tried

**Comment by capaj** [comment]
@zenorocha with this logic, desc should be 'de' or 'des'. Why is it not following the same 2/3 letter pattern? Also I believe all JS programmers use function template more often than any other.

**Comment by zenorocha** [comment]
I would love for `desc` to become `de`, but it's already used in `debugger`. We could use `des` though.

**Comment by zenorocha** [comment]
Which function template JS programmers uses more really depends on their workflow. Some may use more prototypes than simple functions, others may use the [function as a property of an object](https://github.com/zenorocha/atom-javascript-snippets#ofn-function-as-a-property-of-an-object) more, and so on.

**Comment by skyguide** [comment]
@zenorocha that conflict could be solved by having debugger as 'd' instead of 'de'

**Comment by capaj** [comment]
@zenorocha that conflict could be solved by having debugger as 'd' instead of 'de'

**Pull request closed without merging**
